%%%% This code was generated by heta-compiler of v0.9.7
% 

function p = nameless_param()

p = zeros(9, 1);
%%% parameter annotation
p(1) = 10; % kabs_Alc,  () 
p(2) = 3; % Vmax_ADH,  () 
p(3) = 0.1; % Km_ADH,  () 
p(4) = 3; % Vmax_ALDH,  () 
p(5) = 3; % Km_ALDH,  () 
p(6) = 1; % sw1_,  
p(7) = 1; % sw2_,  
p(8) = 1; % gut
p(9) = 5.5; % blood

end