name: Deploy Eleventy site to GitHub Pages

on:
  push:
    branches: [main]          # run every time you push to “main”

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6.0.3

      - uses: actions/setup-node@v6.4.0
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci                 

      - name: Build Eleventy site
        run: npm run build          

      - name: Deploy to "gh-pages"
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: _site # The folder the action should deploy.
          clean: true